{
  try {
    return assertEvent(events.poll(10,TimeUnit.SECONDS));
  }
 catch (  InterruptedException e) {
    throw new AssertionError("No event received within timeout");
  }
}
